# Site settings
title: Forty
subtitle: by HTML5 UP
email: your-email@example.com
description: >-
  A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.

baseurl: "" # Set your subpath if deploying to a folder, e.g. /blog
url: "" # Set your site URL, e.g. http://example.com

author:
  street_address: 1234 Somewhere Road
  city: Nashville
  state: TN
  zip_code: 55555
  country: United States of America
  phone: (716) 555-5555

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# Social settings (keys must match Font Awesome icon names)
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# Build settings
markdown: kramdown
theme: # leave blank if using local theme files
plugins:
  - jekyll-feed

sass:
  style: compressed

# Author usernames (optional)
twitter_username: jekyllrb
github_username: jekyll

# Exclude these files/folders from build
exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
