name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change to 'main' if your default branch is 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Build and Deploy with Jekyll
        uses: helaili/jekyll-action@2.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}